### ISSUE TITLE
Invalid state space representation of Lotka-Volterrra equations ?

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#135]
In http://beta.book.xogeny.com/behavior/equations/population/ you say that "the Lotka-Volterra system of equations is actually non-linear". This is true since bilinear is non-linear in some case.

Later on in http://beta.book.xogeny.com/behavior/arrays/state_space/ you introduce the linear ABCD form of DOEs where system matrix A is either A(t) or time-invariant. However in ArrayEquations.StateSpace.Examples.LotkaVolterra you have an A = A(x), i.e. an A that depends on the state variables. This does not match the state space representation.

**Comment by tbeu** [comment]
While you say "In the section above we do not include a representation of the Lotka-Volterra equations in LTI form" the model ModelicaByExample.ArrayEquations.StateSpace.Examples.LotkaVolterra does exactly this (though not being mentioned).

**Comment by xogeny** [comment]
@tbeu I think what happened was that I included it and then thought it was confusing.  But, I left the model there just as an example.  Since it isn't in the book, I assume only an advanced reader is going to bother looking at models not mentioned in the book.

What might be useful is some kind of comment in the model explaining "This model is in ABCD form but is the A matrix included a nonlinear term.  As such, it can be cast into a general ABCD form that allows the matrices to be both non-linear and time variant.  This form is still useful in some cases because it can be used to compute properties that can be applied *locally* to some region of state space (e.g., natural frequencies)."

Does that address your concern?

**Comment by tbeu** [comment]
Indeed, such a commen to the model would be helpful.
