### ISSUE TITLE
Use KaTeX instead of MathJax?

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#212]
There is a new TeX rendering project that is lightening fast and also can do the rendering on the server side.  Might be worth looking into. Not sure yet how to best combine this with the Sphinx tool chain. 

https://github.com/Khan/KaTeX

**Comment by sjoelund** [comment]
It is also possible to use the kind of hacks I used for OpenModelica-doc: generating static SVGs from Sphinx:
https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omnotebook.html#mathematical-modeling-with-characteristic-equations

They are a bit big and the text cannot be selected since the texts are converted to paths in order to avoid problems with rendering in different browsers.

**Comment by xogeny** [comment]
I'd like to revisit this because the MathJax CDN issue is a big one (the current site spits out lots of warnings about the CDN going away).  It would be nice to be able to avoid using the CDN.  That means possibly serving MathJax ourselves (I suspect that will be complicated).  Alternatively, we could look a KaTeX.  I initially thought you'd have to use JS to render, but there is an [auto-render](https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md) option.  But now that we use Node to build the embedded simulation UI, we could consider using it as well to pre-render all the math as HTML **during the build process** which means it would all be done statically.

Comments?

**Comment by sjoelund** [comment]
For OpenModelica I hacked together SVG generation of the LaTeX code in Sphinx in order to avoid using MathJax to get something that looks nice on most platforms. It wasn't very complicated :)

**Comment by xogeny** [comment]
I'm not using a tool called `mathjax-node-page` which does the MathJax conversion **server-side**.  This means that we shouldn't actually need to load MathJax in the browser (although I haven't figured out a way yet to remove the script element.  I've done a sample build and it seems to be working.  We need to figure out how to do a similar thing with ePub (and Mobi?) as well.

**Comment by xogeny** [comment]
I'm very happy with this solution.  HTML looks very nice, no JS for rendering, no render delay.  Only open question is whether this creates any complications for ebooks.  But I'm going to assume that it won't have an impact.  We can reopen if we find an issue later.
