### ISSUE TITLE
Approximation of pi

### ISSUE THREAD

**Issue by christiankral** [xogeny/ModelicaBook#254]
I noticed that on http://book.xogeny.com/behavior/functions/func_def/ pi is approximated by 3.1415. Considering that pi = 3.1415926535898... the correct approximation with respect to five significant digits is 3.1416.

One problem here is that pi is not inherently defined in Modelica. If one wants to avoid the reference to the Modelica Standard Library where pi is defined as Modelica.Constants.pi, an alternative could be
```constant Real pi = 4*atan(1);```

The approximation issue with pi may apply to different pages, too.

**Comment by dietmarw** [comment]
I would probably suggest to use the same as is used in the MSL:
```
pi=2*Modelica.Math.asin(1.0);
```
so in order to not depend on the whole MSL (if only there were modular imports available ;-) )
```
pi=2*asin(1.0);
```
Of course it *should* give the same result as `atan()` but is more consistent perhaps.

**Comment by xogeny** [comment]
Since `pi` is not actually declared as a variable anywhere on that page, I think it should the solution is to follow Christian's original suggestion and simply make the approximation `3.1416` or perhaps `3.14159`.

I tried to be careful in writing the book to introduce new topics/features/capabilities one at a time.  I don't want to suddenly have a new variable where there wasn't one before since then the explanation in the text might not match.  I don't want to use an expression like `asin(1.0)` because that is precise but a little obfuscated for the reader (it won't be immediately clear to them what that means).

Anybody going to make a pull request? ;-)

**Comment by xogeny** [comment]
:+1: to Dongping for fixing an issue that wasn't even his. :smile:
