### ISSUE TITLE
Mobile Friendliness Problem

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#280]
According to [Google Mobile Test](https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fbook.xogeny.com%2Fcomponents%2Fcomponents%2Fblock_comps%2F%23block-components), the site as it is now is not mobile friendly (probably because of the `min-width` in xogeny.css). 

I'll send a PR to change the `min-width` from `800px` to `320px`. 

However, there are [other issues as shown in my test bucket](https://developers.google.com/speed/pagespeed/insights/?priorityGroup=USABILITY&url=http%3A%2F%2Fcnbook.s3-website-ap-northeast-1.amazonaws.com%2Fcomponents%2Fcomponents%2Frot_comps_adv%2F). 

So i'm opening a ticket.

**Comment by xogeny** [comment]
I assume this is resolved with the merged pull request?

**Comment by dietmarw** [comment]
It looks like the landing page has still issues and is marked as non-mobile friendly. The content pages themselves get a: 
![image](https://user-images.githubusercontent.com/9332/33128782-f2d59902-cf8d-11e7-99c3-f10f9811475b.png)

**Comment by xogeny** [comment]
The Google analysis is flakey.  I requested an analysis and got a ton of issues and the landing page didn't really render properly at all.  I asked it to do the analysis again and it came back with only one issue.  It seems to have some issue with loading resources from the site, but it definitely should not (these are being serviced from Amazon S3, I have very little control over this and I'm dubious that S3 has a problem here).

As a result, I'm going to close this for now since I cannot reliably detect any issues at the moment.
