### ISSUE TITLE
Missing: Overloaded operators

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#345]
A customer asked about some documentation at overloaded operators (except the MLS, section 14) and I noticed that it is missing in the book. It is planned to add some information on it?

**Comment by xogeny** [comment]
There are several things missing in the book.  This is actually deliberate.  There are certain topics in Modelica that are very complicated but not of general interest.  I chose to leave those out simply because a) I didn't want to make the language appear intimidating and complicated, b) I felt it would be a potential distraction to those trying to learn the basics of the language and c) they can still learn those aspects of the language from other sources (i.e., the specification).

But thanks for raising this question.  I'd like to try and polish up any incomplete sections of the book.  It is just that this isn't really one of them.

**Comment by tbeu** [comment]
Thanks for the feedback. I can live with it.
